.Dd January 13, 2015
.Dt WINDOW-NAME 1
.Os xcbh
.Sh NAME
.Nm window-name
.Nd print window name
.Sh SYNOPSIS
.Nm wname
.Ar wid Op ...
.Sh DESCRIPTION
.Nm
prints the name of the window IDs given as arguments,
one name per line.
.Sh ENVIRONMENT
.Nm
acts on the X display specified by the
.Ev DISPLAY
variable.
