/* SEE LICENSE */

#include "xcmd.h"

xcmd_call (2, "event-dir") {
	char *event_dir;
	xcb_window_t *win;
	xcb_screen_t *screen;
	uint32_t mask = XCB_EVENT_MASK_NO_EVENT
		| XCB_EVENT_MASK_KEY_PRESS
		| XCB_EVENT_MASK_KEY_RELEASE
		| XCB_EVENT_MASK_BUTTON_PRESS
		| XCB_EVENT_MASK_BUTTON_RELEASE
		| XCB_EVENT_MASK_ENTER_WINDOW
		| XCB_EVENT_MASK_LEAVE_WINDOW
		| XCB_EVENT_MASK_POINTER_MOTION
		| XCB_EVENT_MASK_POINTER_MOTION_HINT
		| XCB_EVENT_MASK_BUTTON_1_MOTION
		| XCB_EVENT_MASK_BUTTON_2_MOTION
		| XCB_EVENT_MASK_BUTTON_3_MOTION
		| XCB_EVENT_MASK_BUTTON_4_MOTION
		| XCB_EVENT_MASK_BUTTON_5_MOTION
		| XCB_EVENT_MASK_BUTTON_MOTION
		| XCB_EVENT_MASK_KEYMAP_STATE
		| XCB_EVENT_MASK_EXPOSURE
		| XCB_EVENT_MASK_VISIBILITY_CHANGE
		| XCB_EVENT_MASK_STRUCTURE_NOTIFY
		| XCB_EVENT_MASK_RESIZE_REDIRECT
		| XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY
		| XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT
		| XCB_EVENT_MASK_FOCUS_CHANGE
		| XCB_EVENT_MASK_PROPERTY_CHANGE
		| XCB_EVENT_MASK_COLOR_MAP_CHANGE
		| XCB_EVENT_MASK_OWNER_GRAB_BUTTON;

	xcbtools_screen_init(xcmd_conn, &screen);

	event_dir = xcmd_next;

	xcbtools_event_register(xcmd_conn, screen->root, XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY);
	xcbtools_window_children(xcmd_conn, screen->root, &win);

	while (*win++) {
		xcbtools_event_register(xcmd_conn, *win, mask);
	}

	xcbtools_event_loop(xcmd_conn, event_dir);

	xcmd_exit(0);
}
