#!/bin/bash

if (window-is-valid $WINDOW); then
	window-border 2 770099 $WINDOW
	sleep 0.15
	window-border 2 660088 $WINDOW
	sleep 0.09
	window-border 2 550077 $WINDOW
	sleep 0.06
	window-border 2 550066 $WINDOW
	sleep 0.07
	window-border 2 440055 $WINDOW
fi

